/** Datos legales de la empresa y estilos compartidos por los PDF de OC/OV. */
import { StyleSheet } from "@react-pdf/renderer";
import { VERDE, VERDE_SUAVE, GRIS } from "./empresa-datos";

export {
  EMPRESA,
  LOGO_URL_ABS,
  VERDE,
  VERDE_SUAVE,
  GRIS,
  fmtCLP,
  fmtFechaLarga,
  PAGO_LABEL,
  pagoLabel,
} from "./empresa-datos";

export const ordenStyles = StyleSheet.create({
  page: { paddingTop: 32, paddingBottom: 56, paddingHorizontal: 36, fontSize: 9, color: "#1F2937" },
  headerRow: { flexDirection: "row", justifyContent: "space-between", alignItems: "flex-start" },
  marcaBloque: { flexDirection: "row", alignItems: "center", gap: 8 },
  logo: { width: 44, height: 44, borderRadius: 22, objectFit: "contain" },
  marca: { fontSize: 24, fontWeight: "bold", color: VERDE, letterSpacing: 1 },
  tagline: { fontSize: 8, fontStyle: "italic", color: GRIS, marginTop: 3 },
  docTitulo: { fontSize: 18, fontWeight: "bold", textAlign: "right" },
  docMeta: { fontSize: 8, color: GRIS, textAlign: "right", marginTop: 2 },
  divider: { borderBottomWidth: 2, borderBottomColor: VERDE, marginTop: 12, marginBottom: 14 },
  cols: { flexDirection: "row", gap: 18 },
  col: { flex: 1 },
  seccionTitulo: {
    fontSize: 9,
    fontWeight: "bold",
    color: VERDE,
    marginBottom: 5,
    letterSpacing: 0.5,
  },
  linea: { flexDirection: "row", marginBottom: 2 },
  etiqueta: { width: 78, color: GRIS },
  valor: { flex: 1 },
  tituloServicio: { marginTop: 16, fontSize: 12, fontWeight: "bold" },
  rutaLinea: { marginTop: 4, fontSize: 9 },
  bloqueChofer: { marginTop: 12, backgroundColor: VERDE_SUAVE, padding: 7, fontSize: 8.5 },
  tabla: { marginTop: 16, borderWidth: 1, borderColor: "#D1D5DB" },
  tablaHeader: { flexDirection: "row", backgroundColor: VERDE },
  th: { color: "#FFFFFF", fontWeight: "bold", padding: 5, fontSize: 8.5 },
  tr: { flexDirection: "row" },
  td: { padding: 5, fontSize: 8.5 },
  cDesc: { flex: 3 },
  cCant: { flex: 1, textAlign: "right" },
  cUnit: { flex: 1.4, textAlign: "right" },
  cTotal: { flex: 1.4, textAlign: "right" },
  totales: { marginTop: 12, alignItems: "flex-end" },
  totalLinea: { flexDirection: "row", width: 210, justifyContent: "space-between", marginBottom: 3 },
  totalFinal: {
    flexDirection: "row",
    width: 210,
    justifyContent: "space-between",
    marginTop: 5,
    paddingTop: 5,
    borderTopWidth: 1,
    borderTopColor: VERDE,
  },
  totalFinalTexto: { fontSize: 12, fontWeight: "bold", color: VERDE },
  seccion: { marginTop: 16 },
  nota: { marginTop: 8, backgroundColor: VERDE_SUAVE, padding: 7, fontSize: 8.5 },
  footer: {
    position: "absolute",
    bottom: 26,
    left: 36,
    right: 36,
    borderTopWidth: 1,
    borderTopColor: "#E5E7EB",
    paddingTop: 6,
  },
  footerTexto: { fontSize: 7.5, color: GRIS, textAlign: "center" },
});
