/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterClienteRouteImport } from './routes/register-cliente'
import { Route as RegisterChoferRouteImport } from './routes/register-chofer'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InvitacionChoferTokenRouteImport } from './routes/invitacion-chofer.$token'
import { Route as AppTarifasRouteImport } from './routes/_app.tarifas'
import { Route as AppPerfilRouteImport } from './routes/_app.perfil'
import { Route as AppOperacionesDisponibilidadMapaRouteImport } from './routes/_app.operaciones-disponibilidad-mapa'
import { Route as AppOperacionesCotizacionesRouteImport } from './routes/_app.operaciones-cotizaciones'
import { Route as AppOperacionesAsignacionesRouteImport } from './routes/_app.operaciones-asignaciones'
import { Route as AppOperacionesRouteImport } from './routes/_app.operaciones'
import { Route as AppMisViajesRouteImport } from './routes/_app.mis-viajes'
import { Route as AppMiDisponibilidadChoferRouteImport } from './routes/_app.mi-disponibilidad-chofer'
import { Route as AppMiDisponibilidadRouteImport } from './routes/_app.mi-disponibilidad'
import { Route as AppMensajesRouteImport } from './routes/_app.mensajes'
import { Route as AppDocumentosRouteImport } from './routes/_app.documentos'
import { Route as AppDisponibilidadChoferesRouteImport } from './routes/_app.disponibilidad-choferes'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppComparadorRouteImport } from './routes/_app.comparador'
import { Route as AppClienteRouteImport } from './routes/_app.cliente'
import { Route as AppChoferesRouteImport } from './routes/_app.choferes'
import { Route as AppChoferRouteImport } from './routes/_app.chofer'
import { Route as AppCamionesRouteImport } from './routes/_app.camiones'
import { Route as AppAdminChoferesRouteImport } from './routes/_app.admin-choferes'
import { Route as AppAdminRouteImport } from './routes/_app.admin'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterClienteRoute = RegisterClienteRouteImport.update({
  id: '/register-cliente',
  path: '/register-cliente',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterChoferRoute = RegisterChoferRouteImport.update({
  id: '/register-chofer',
  path: '/register-chofer',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InvitacionChoferTokenRoute = InvitacionChoferTokenRouteImport.update({
  id: '/invitacion-chofer/$token',
  path: '/invitacion-chofer/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTarifasRoute = AppTarifasRouteImport.update({
  id: '/tarifas',
  path: '/tarifas',
  getParentRoute: () => AppRoute,
} as any)
const AppPerfilRoute = AppPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AppRoute,
} as any)
const AppOperacionesDisponibilidadMapaRoute =
  AppOperacionesDisponibilidadMapaRouteImport.update({
    id: '/operaciones-disponibilidad-mapa',
    path: '/operaciones-disponibilidad-mapa',
    getParentRoute: () => AppRoute,
  } as any)
const AppOperacionesCotizacionesRoute =
  AppOperacionesCotizacionesRouteImport.update({
    id: '/operaciones-cotizaciones',
    path: '/operaciones-cotizaciones',
    getParentRoute: () => AppRoute,
  } as any)
const AppOperacionesAsignacionesRoute =
  AppOperacionesAsignacionesRouteImport.update({
    id: '/operaciones-asignaciones',
    path: '/operaciones-asignaciones',
    getParentRoute: () => AppRoute,
  } as any)
const AppOperacionesRoute = AppOperacionesRouteImport.update({
  id: '/operaciones',
  path: '/operaciones',
  getParentRoute: () => AppRoute,
} as any)
const AppMisViajesRoute = AppMisViajesRouteImport.update({
  id: '/mis-viajes',
  path: '/mis-viajes',
  getParentRoute: () => AppRoute,
} as any)
const AppMiDisponibilidadChoferRoute =
  AppMiDisponibilidadChoferRouteImport.update({
    id: '/mi-disponibilidad-chofer',
    path: '/mi-disponibilidad-chofer',
    getParentRoute: () => AppRoute,
  } as any)
const AppMiDisponibilidadRoute = AppMiDisponibilidadRouteImport.update({
  id: '/mi-disponibilidad',
  path: '/mi-disponibilidad',
  getParentRoute: () => AppRoute,
} as any)
const AppMensajesRoute = AppMensajesRouteImport.update({
  id: '/mensajes',
  path: '/mensajes',
  getParentRoute: () => AppRoute,
} as any)
const AppDocumentosRoute = AppDocumentosRouteImport.update({
  id: '/documentos',
  path: '/documentos',
  getParentRoute: () => AppRoute,
} as any)
const AppDisponibilidadChoferesRoute =
  AppDisponibilidadChoferesRouteImport.update({
    id: '/disponibilidad-choferes',
    path: '/disponibilidad-choferes',
    getParentRoute: () => AppRoute,
  } as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppComparadorRoute = AppComparadorRouteImport.update({
  id: '/comparador',
  path: '/comparador',
  getParentRoute: () => AppRoute,
} as any)
const AppClienteRoute = AppClienteRouteImport.update({
  id: '/cliente',
  path: '/cliente',
  getParentRoute: () => AppRoute,
} as any)
const AppChoferesRoute = AppChoferesRouteImport.update({
  id: '/choferes',
  path: '/choferes',
  getParentRoute: () => AppRoute,
} as any)
const AppChoferRoute = AppChoferRouteImport.update({
  id: '/chofer',
  path: '/chofer',
  getParentRoute: () => AppRoute,
} as any)
const AppCamionesRoute = AppCamionesRouteImport.update({
  id: '/camiones',
  path: '/camiones',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminChoferesRoute = AppAdminChoferesRouteImport.update({
  id: '/admin-choferes',
  path: '/admin-choferes',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/register-chofer': typeof RegisterChoferRoute
  '/register-cliente': typeof RegisterClienteRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin': typeof AppAdminRoute
  '/admin-choferes': typeof AppAdminChoferesRoute
  '/camiones': typeof AppCamionesRoute
  '/chofer': typeof AppChoferRoute
  '/choferes': typeof AppChoferesRoute
  '/cliente': typeof AppClienteRoute
  '/comparador': typeof AppComparadorRoute
  '/dashboard': typeof AppDashboardRoute
  '/disponibilidad-choferes': typeof AppDisponibilidadChoferesRoute
  '/documentos': typeof AppDocumentosRoute
  '/mensajes': typeof AppMensajesRoute
  '/mi-disponibilidad': typeof AppMiDisponibilidadRoute
  '/mi-disponibilidad-chofer': typeof AppMiDisponibilidadChoferRoute
  '/mis-viajes': typeof AppMisViajesRoute
  '/operaciones': typeof AppOperacionesRoute
  '/operaciones-asignaciones': typeof AppOperacionesAsignacionesRoute
  '/operaciones-cotizaciones': typeof AppOperacionesCotizacionesRoute
  '/operaciones-disponibilidad-mapa': typeof AppOperacionesDisponibilidadMapaRoute
  '/perfil': typeof AppPerfilRoute
  '/tarifas': typeof AppTarifasRoute
  '/invitacion-chofer/$token': typeof InvitacionChoferTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/register-chofer': typeof RegisterChoferRoute
  '/register-cliente': typeof RegisterClienteRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin': typeof AppAdminRoute
  '/admin-choferes': typeof AppAdminChoferesRoute
  '/camiones': typeof AppCamionesRoute
  '/chofer': typeof AppChoferRoute
  '/choferes': typeof AppChoferesRoute
  '/cliente': typeof AppClienteRoute
  '/comparador': typeof AppComparadorRoute
  '/dashboard': typeof AppDashboardRoute
  '/disponibilidad-choferes': typeof AppDisponibilidadChoferesRoute
  '/documentos': typeof AppDocumentosRoute
  '/mensajes': typeof AppMensajesRoute
  '/mi-disponibilidad': typeof AppMiDisponibilidadRoute
  '/mi-disponibilidad-chofer': typeof AppMiDisponibilidadChoferRoute
  '/mis-viajes': typeof AppMisViajesRoute
  '/operaciones': typeof AppOperacionesRoute
  '/operaciones-asignaciones': typeof AppOperacionesAsignacionesRoute
  '/operaciones-cotizaciones': typeof AppOperacionesCotizacionesRoute
  '/operaciones-disponibilidad-mapa': typeof AppOperacionesDisponibilidadMapaRoute
  '/perfil': typeof AppPerfilRoute
  '/tarifas': typeof AppTarifasRoute
  '/invitacion-chofer/$token': typeof InvitacionChoferTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/register-chofer': typeof RegisterChoferRoute
  '/register-cliente': typeof RegisterClienteRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_app/admin': typeof AppAdminRoute
  '/_app/admin-choferes': typeof AppAdminChoferesRoute
  '/_app/camiones': typeof AppCamionesRoute
  '/_app/chofer': typeof AppChoferRoute
  '/_app/choferes': typeof AppChoferesRoute
  '/_app/cliente': typeof AppClienteRoute
  '/_app/comparador': typeof AppComparadorRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/disponibilidad-choferes': typeof AppDisponibilidadChoferesRoute
  '/_app/documentos': typeof AppDocumentosRoute
  '/_app/mensajes': typeof AppMensajesRoute
  '/_app/mi-disponibilidad': typeof AppMiDisponibilidadRoute
  '/_app/mi-disponibilidad-chofer': typeof AppMiDisponibilidadChoferRoute
  '/_app/mis-viajes': typeof AppMisViajesRoute
  '/_app/operaciones': typeof AppOperacionesRoute
  '/_app/operaciones-asignaciones': typeof AppOperacionesAsignacionesRoute
  '/_app/operaciones-cotizaciones': typeof AppOperacionesCotizacionesRoute
  '/_app/operaciones-disponibilidad-mapa': typeof AppOperacionesDisponibilidadMapaRoute
  '/_app/perfil': typeof AppPerfilRoute
  '/_app/tarifas': typeof AppTarifasRoute
  '/invitacion-chofer/$token': typeof InvitacionChoferTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/register-chofer'
    | '/register-cliente'
    | '/reset-password'
    | '/sitemap.xml'
    | '/admin'
    | '/admin-choferes'
    | '/camiones'
    | '/chofer'
    | '/choferes'
    | '/cliente'
    | '/comparador'
    | '/dashboard'
    | '/disponibilidad-choferes'
    | '/documentos'
    | '/mensajes'
    | '/mi-disponibilidad'
    | '/mi-disponibilidad-chofer'
    | '/mis-viajes'
    | '/operaciones'
    | '/operaciones-asignaciones'
    | '/operaciones-cotizaciones'
    | '/operaciones-disponibilidad-mapa'
    | '/perfil'
    | '/tarifas'
    | '/invitacion-chofer/$token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/register-chofer'
    | '/register-cliente'
    | '/reset-password'
    | '/sitemap.xml'
    | '/admin'
    | '/admin-choferes'
    | '/camiones'
    | '/chofer'
    | '/choferes'
    | '/cliente'
    | '/comparador'
    | '/dashboard'
    | '/disponibilidad-choferes'
    | '/documentos'
    | '/mensajes'
    | '/mi-disponibilidad'
    | '/mi-disponibilidad-chofer'
    | '/mis-viajes'
    | '/operaciones'
    | '/operaciones-asignaciones'
    | '/operaciones-cotizaciones'
    | '/operaciones-disponibilidad-mapa'
    | '/perfil'
    | '/tarifas'
    | '/invitacion-chofer/$token'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/register-chofer'
    | '/register-cliente'
    | '/reset-password'
    | '/sitemap.xml'
    | '/_app/admin'
    | '/_app/admin-choferes'
    | '/_app/camiones'
    | '/_app/chofer'
    | '/_app/choferes'
    | '/_app/cliente'
    | '/_app/comparador'
    | '/_app/dashboard'
    | '/_app/disponibilidad-choferes'
    | '/_app/documentos'
    | '/_app/mensajes'
    | '/_app/mi-disponibilidad'
    | '/_app/mi-disponibilidad-chofer'
    | '/_app/mis-viajes'
    | '/_app/operaciones'
    | '/_app/operaciones-asignaciones'
    | '/_app/operaciones-cotizaciones'
    | '/_app/operaciones-disponibilidad-mapa'
    | '/_app/perfil'
    | '/_app/tarifas'
    | '/invitacion-chofer/$token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  RegisterChoferRoute: typeof RegisterChoferRoute
  RegisterClienteRoute: typeof RegisterClienteRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  InvitacionChoferTokenRoute: typeof InvitacionChoferTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register-cliente': {
      id: '/register-cliente'
      path: '/register-cliente'
      fullPath: '/register-cliente'
      preLoaderRoute: typeof RegisterClienteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register-chofer': {
      id: '/register-chofer'
      path: '/register-chofer'
      fullPath: '/register-chofer'
      preLoaderRoute: typeof RegisterChoferRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invitacion-chofer/$token': {
      id: '/invitacion-chofer/$token'
      path: '/invitacion-chofer/$token'
      fullPath: '/invitacion-chofer/$token'
      preLoaderRoute: typeof InvitacionChoferTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/tarifas': {
      id: '/_app/tarifas'
      path: '/tarifas'
      fullPath: '/tarifas'
      preLoaderRoute: typeof AppTarifasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/perfil': {
      id: '/_app/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AppPerfilRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/operaciones-disponibilidad-mapa': {
      id: '/_app/operaciones-disponibilidad-mapa'
      path: '/operaciones-disponibilidad-mapa'
      fullPath: '/operaciones-disponibilidad-mapa'
      preLoaderRoute: typeof AppOperacionesDisponibilidadMapaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/operaciones-cotizaciones': {
      id: '/_app/operaciones-cotizaciones'
      path: '/operaciones-cotizaciones'
      fullPath: '/operaciones-cotizaciones'
      preLoaderRoute: typeof AppOperacionesCotizacionesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/operaciones-asignaciones': {
      id: '/_app/operaciones-asignaciones'
      path: '/operaciones-asignaciones'
      fullPath: '/operaciones-asignaciones'
      preLoaderRoute: typeof AppOperacionesAsignacionesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/operaciones': {
      id: '/_app/operaciones'
      path: '/operaciones'
      fullPath: '/operaciones'
      preLoaderRoute: typeof AppOperacionesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/mis-viajes': {
      id: '/_app/mis-viajes'
      path: '/mis-viajes'
      fullPath: '/mis-viajes'
      preLoaderRoute: typeof AppMisViajesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/mi-disponibilidad-chofer': {
      id: '/_app/mi-disponibilidad-chofer'
      path: '/mi-disponibilidad-chofer'
      fullPath: '/mi-disponibilidad-chofer'
      preLoaderRoute: typeof AppMiDisponibilidadChoferRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/mi-disponibilidad': {
      id: '/_app/mi-disponibilidad'
      path: '/mi-disponibilidad'
      fullPath: '/mi-disponibilidad'
      preLoaderRoute: typeof AppMiDisponibilidadRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/mensajes': {
      id: '/_app/mensajes'
      path: '/mensajes'
      fullPath: '/mensajes'
      preLoaderRoute: typeof AppMensajesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/documentos': {
      id: '/_app/documentos'
      path: '/documentos'
      fullPath: '/documentos'
      preLoaderRoute: typeof AppDocumentosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/disponibilidad-choferes': {
      id: '/_app/disponibilidad-choferes'
      path: '/disponibilidad-choferes'
      fullPath: '/disponibilidad-choferes'
      preLoaderRoute: typeof AppDisponibilidadChoferesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/comparador': {
      id: '/_app/comparador'
      path: '/comparador'
      fullPath: '/comparador'
      preLoaderRoute: typeof AppComparadorRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/cliente': {
      id: '/_app/cliente'
      path: '/cliente'
      fullPath: '/cliente'
      preLoaderRoute: typeof AppClienteRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/choferes': {
      id: '/_app/choferes'
      path: '/choferes'
      fullPath: '/choferes'
      preLoaderRoute: typeof AppChoferesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/chofer': {
      id: '/_app/chofer'
      path: '/chofer'
      fullPath: '/chofer'
      preLoaderRoute: typeof AppChoferRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/camiones': {
      id: '/_app/camiones'
      path: '/camiones'
      fullPath: '/camiones'
      preLoaderRoute: typeof AppCamionesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin-choferes': {
      id: '/_app/admin-choferes'
      path: '/admin-choferes'
      fullPath: '/admin-choferes'
      preLoaderRoute: typeof AppAdminChoferesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRoute
  AppAdminChoferesRoute: typeof AppAdminChoferesRoute
  AppCamionesRoute: typeof AppCamionesRoute
  AppChoferRoute: typeof AppChoferRoute
  AppChoferesRoute: typeof AppChoferesRoute
  AppClienteRoute: typeof AppClienteRoute
  AppComparadorRoute: typeof AppComparadorRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppDisponibilidadChoferesRoute: typeof AppDisponibilidadChoferesRoute
  AppDocumentosRoute: typeof AppDocumentosRoute
  AppMensajesRoute: typeof AppMensajesRoute
  AppMiDisponibilidadRoute: typeof AppMiDisponibilidadRoute
  AppMiDisponibilidadChoferRoute: typeof AppMiDisponibilidadChoferRoute
  AppMisViajesRoute: typeof AppMisViajesRoute
  AppOperacionesRoute: typeof AppOperacionesRoute
  AppOperacionesAsignacionesRoute: typeof AppOperacionesAsignacionesRoute
  AppOperacionesCotizacionesRoute: typeof AppOperacionesCotizacionesRoute
  AppOperacionesDisponibilidadMapaRoute: typeof AppOperacionesDisponibilidadMapaRoute
  AppPerfilRoute: typeof AppPerfilRoute
  AppTarifasRoute: typeof AppTarifasRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRoute,
  AppAdminChoferesRoute: AppAdminChoferesRoute,
  AppCamionesRoute: AppCamionesRoute,
  AppChoferRoute: AppChoferRoute,
  AppChoferesRoute: AppChoferesRoute,
  AppClienteRoute: AppClienteRoute,
  AppComparadorRoute: AppComparadorRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppDisponibilidadChoferesRoute: AppDisponibilidadChoferesRoute,
  AppDocumentosRoute: AppDocumentosRoute,
  AppMensajesRoute: AppMensajesRoute,
  AppMiDisponibilidadRoute: AppMiDisponibilidadRoute,
  AppMiDisponibilidadChoferRoute: AppMiDisponibilidadChoferRoute,
  AppMisViajesRoute: AppMisViajesRoute,
  AppOperacionesRoute: AppOperacionesRoute,
  AppOperacionesAsignacionesRoute: AppOperacionesAsignacionesRoute,
  AppOperacionesCotizacionesRoute: AppOperacionesCotizacionesRoute,
  AppOperacionesDisponibilidadMapaRoute: AppOperacionesDisponibilidadMapaRoute,
  AppPerfilRoute: AppPerfilRoute,
  AppTarifasRoute: AppTarifasRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  RegisterChoferRoute: RegisterChoferRoute,
  RegisterClienteRoute: RegisterClienteRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  InvitacionChoferTokenRoute: InvitacionChoferTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
